# -*- coding: utf-8 -*-
"""AS1-NB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Qchxz_7_Rh3T2Lq72o-QHEmYMPrekOy

# Assignment 1: Data Analytics

In this assignment, you will carry out a structured data analytics exercise using a real-world dataset automatically assigned to you from OpenML. The purpose of the assignment is to develop your ability to **interpret quantitative data**, **reason about data quality**, and **communicate analytical insights using numerical evidence**.

You will work through a sequence of tasks that reflect a typical analytics workflow. The notebook provides all necessary computational steps for loading the data, inspecting its structure, cleaning missing values, computing descriptive statistics, and identifying correlations. Your role is **not to write analytical code**, but to **run the provided cells, examine the outputs carefully, and produce evidence-based analysis** based on what you observe.

Throughout the assignment, you will be asked to interpret results such as dataset size, variable types, missingness patterns, summary statistics, outliers, and correlations. You will then synthesise these observations into short analytical responses and a final reflection that integrates findings across all tasks. Strong submissions will reference specific numerical results and clearly explain what those results imply about the dataset and the analysis performed.

By the end of this assignment, you should be able to:
- Understand and describe the structure and content of a quantitative dataset
- Evaluate data quality and the impact of cleaning decisions
- Interpret statistical summaries and relationships between variables
- Communicate analytical reasoning clearly using quantitative evidence

This assignment emphasises **analytical thinking and interpretation**, rather than programming. Python is used here as a measurement and inspection tool, similar to a calculator in engineering practice.

## Task 1 — Dataset assignment (OpenML, Quantitative-Only)

Run the Python cell below to:
1) Build a candidate pool of OpenML datasets designed for **quantitative analytics**:
   - Mostly numeric features (numeric-heavy)
   - Large enough for meaningful analytics
   - Has missing values (so you can do cleaning)
2) Assign you one dataset deterministically based on your student ID.
3) Validate that the loaded dataset is truly numeric-heavy; if not, the code automatically moves to the next dataset in the pool.

Deliverables:
- The printed values for:
  - `OPENML_DID`, `DATASET_NAME`, `N_ROWS`, `N_COLS`, `NUMERIC_RATIO_LOADED`
- These values are stored automatically for your final JSON submission.

This task assigns your dataset automatically.

You are NOT assessed on this task.

You should:
- Run the cell
- Record the dataset name and size
- Use these values later when interpreting results
"""

!pip -q install openml

# ========= STUDENT MUST FILL =========
STUDENT_ID = "1615838"   # REQUIRED (string), e.g., "202612345"

# =========================
# TASK 1 — Quantitative-only dataset assignment (OpenML + validation)
# =========================

# In Colab you may need:
# !pip -q install openml

import re
import json
import numpy as np
import pandas as pd
import openml

if not STUDENT_ID.strip():
    raise ValueError("Fill STUDENT_ID before running.")

digits = re.sub(r"\D+", "", STUDENT_ID)
sid_num = int(digits) if digits else abs(hash(STUDENT_ID)) % (10**12)

dlist = openml.datasets.list_datasets(output_format="dataframe")

needed_cols = [
    "did", "name",
    "NumberOfInstances", "NumberOfFeatures",
    "NumberOfMissingValues",
    "NumberOfNumericFeatures", "NumberOfSymbolicFeatures"
]
for c in needed_cols:
    if c not in dlist.columns:
        dlist[c] = np.nan

# ---- Pool filters (instructor-tuned defaults) ----
MIN_ROWS = 100
MIN_FEATURES = 8
MAX_FEATURES = 2000
REQUIRE_MISSING = True

MIN_NUMERIC_RATIO_META = 0.85
MAX_SYMBOLIC_RATIO_META = 0.10

# Post-load (hard) quantitative requirement:
MIN_NUMERIC_RATIO_LOADED = 0.80
MAX_TRIES = 25  # deterministic fallback window

pool = dlist.copy()
pool = pool.dropna(subset=["did", "NumberOfInstances", "NumberOfFeatures"])
pool = pool[
    (pool["NumberOfInstances"] >= MIN_ROWS) &
    (pool["NumberOfFeatures"] >= MIN_FEATURES) &
    (pool["NumberOfFeatures"] <= MAX_FEATURES)
]
pool = pool.dropna(subset=["NumberOfNumericFeatures", "NumberOfSymbolicFeatures"], how="any")

numeric_ratio_meta = pool["NumberOfNumericFeatures"] / pool["NumberOfFeatures"]
symbolic_ratio_meta = pool["NumberOfSymbolicFeatures"] / pool["NumberOfFeatures"]

pool = pool[
    (numeric_ratio_meta >= MIN_NUMERIC_RATIO_META) &
    (symbolic_ratio_meta <= MAX_SYMBOLIC_RATIO_META)
]

if REQUIRE_MISSING:
    pool = pool.dropna(subset=["NumberOfMissingValues"])
    pool = pool[pool["NumberOfMissingValues"] > 0]

pool = pool.sort_values(["NumberOfInstances", "NumberOfFeatures"], ascending=[False, False]).reset_index(drop=True)

if len(pool) < 30:
    raise RuntimeError(
        f"Pool too small ({len(pool)}). Instructor should relax MIN_ROWS / MIN_NUMERIC_RATIO_META / REQUIRE_MISSING."
    )

def _load_and_numeric_ratio(did: int):
    ds = openml.datasets.get_dataset(int(did))
    X, y, categorical_indicator, attribute_names = ds.get_data(
        dataset_format="dataframe",
        target=ds.default_target_attribute
    )
    X_num = X.apply(pd.to_numeric, errors="coerce")
    n_numeric_cols = int((~X_num.isna().all()).sum())
    numeric_ratio_loaded = n_numeric_cols / max(1, X.shape[1])
    return ds, X, y, numeric_ratio_loaded

start_idx = sid_num % len(pool)

chosen = None
for k in range(MAX_TRIES):
    idx = (start_idx + k) % len(pool)
    OPENML_DID = int(pool.loc[idx, "did"])
    DATASET_NAME = str(pool.loc[idx, "name"])

    try:
        ds, X, y, NUMERIC_RATIO_LOADED = _load_and_numeric_ratio(OPENML_DID)
    except Exception:
        continue

    if X.shape[0] >= MIN_ROWS and X.shape[1] >= MIN_FEATURES and NUMERIC_RATIO_LOADED >= MIN_NUMERIC_RATIO_LOADED:
        chosen = True
        break

if not chosen:
    raise RuntimeError(
        "Could not find a suitable quantitative dataset within fallback window. "
        "Instructor should relax MIN_NUMERIC_RATIO_LOADED or increase MAX_TRIES."
    )

N_ROWS, N_COLS = X.shape

print("Assigned dataset (quantitative-only):")
print("  STUDENT_ID           =", STUDENT_ID)
print("  POOL_SIZE            =", len(pool))
print("  OPENML_DID           =", OPENML_DID)
print("  DATASET_NAME         =", DATASET_NAME)
print("  N_ROWS               =", N_ROWS)
print("  N_COLS               =", N_COLS)
print("  NUMERIC_RATIO_LOADED =", round(NUMERIC_RATIO_LOADED, 3))

submission = {
    "student_id": STUDENT_ID,
    "openml_did": int(OPENML_DID),
    "dataset_name": str(DATASET_NAME),
    "n_rows_raw": int(N_ROWS),
    "n_cols_raw": int(N_COLS),
    "numeric_ratio_loaded": float(round(NUMERIC_RATIO_LOADED, 6)),
    "min_numeric_ratio_loaded_required": float(MIN_NUMERIC_RATIO_LOADED),
}

# =========================
# TASK 1B — Student input (dataset context)
# =========================

DATASET_CONTEXT = (
    "This dataset appears to describe a financial or economic process, "
    "based on the dataset name and several variables related to income, "
    "accounts, and rates. This interpretation is based solely on the column names "
    "and metadata, not on any external documentation. /1"
)

if len(DATASET_CONTEXT.strip().split()) < 25:
    raise ValueError("DATASET_CONTEXT must be at least 25 words (2–3 sentences).")

submission.update({
    "dataset_context": DATASET_CONTEXT.strip()
})

"""## Task 2 — Dataset report (content + dimensionality + quick metadata)

Run the Python cell below to generate a compact dataset report.

Deliverables:
- Print:
  - Column names (first ~20)
  - Data types summary
  - Basic shape and memory usage estimate
  - Target column name (if available) and whether you will use it or ignore it for this analytics-only assignment
- These outputs must update the `submission` dictionary automatically.

You will NOT be marked on modifying the code.

Your assessment is based on how well you use these results in your written analysis later.
"""

# =========================
# TASK 2 — Dataset report (content + dimensionality + metadata)
# =========================

print("X.head():")
display(X.head())

dtype_counts = X.dtypes.astype(str).value_counts()
print("\nDtype counts:")
print(dtype_counts)

mem_mb = X.memory_usage(deep=True).sum() / (1024**2)
print(f"\nApprox. memory usage (features table): {mem_mb:.2f} MB")

TARGET_NAME = ds.default_target_attribute
print("\nDefault target attribute reported by OpenML:")
print("  TARGET_NAME =", TARGET_NAME)

# ========= STUDENT MUST CHOOSE =========
USE_TARGET = False
# ======================================

submission.update({
    "target_name": None if TARGET_NAME is None else str(TARGET_NAME),
    "use_target": bool(USE_TARGET),
    "dtype_counts_raw": {k: int(v) for k, v in dtype_counts.to_dict().items()},
    "memory_mb_features_raw": float(round(mem_mb, 4)),
})

# =========================
# TASK 2B — Student input (interpret the dataset report)
# =========================

DATASET_DESCRIPTION = (
    "Based on the column names and previewed values, this dataset represents "
    "structured records describing a real-world quantitative system. The variables "
    "suggest measurements collected across many instances, with each row "
    "representing an individual observation. /1"
)

TARGET_DECISION = (
    "The target variable is not used in this analysis because the focus of the "
    "assignment is exploratory data analytics rather than prediction. Ignoring "
    "the target allows unbiased examination of feature relationships. /1"
)

DATA_TYPES_COMMENT = (
    "Most variables are numeric, indicating that this dataset is suitable for "
    "quantitative statistical analysis. Although some variables may represent "
    "encoded categories, their numeric form enables summary statistics and "
    "correlation analysis. /1"
)

# Simple quality checks
if len(DATASET_DESCRIPTION.strip().split()) < 25:
    raise ValueError("DATASET_DESCRIPTION must be at least ~25 words.")
if len(TARGET_DECISION.strip().split()) < 25:
    raise ValueError("TARGET_DECISION must be at least ~25 words.")
if len(DATA_TYPES_COMMENT.strip().split()) < 25:
    raise ValueError("DATA_TYPES_COMMENT must be at least ~25 words.")

# Encourage evidence: at least one number somewhere across these fields
combined = f"{DATASET_DESCRIPTION} {TARGET_DECISION} {DATA_TYPES_COMMENT}"
if not any(ch.isdigit() for ch in combined):
    raise ValueError("In Task 2B, include at least one numeric fact (e.g., rows, cols, memory MB, dtype counts).")

submission.update({
    "dataset_description": DATASET_DESCRIPTION.strip(),
    "target_decision": TARGET_DECISION.strip(),
    "data_types_comment": DATA_TYPES_COMMENT.strip(),
})

"""## Task 3 — EDA for missingness and data cleanup

Run the Python cell below to:
1) Identify missing values per column and overall missingness rate.
2) Decide on a cleaning strategy (you must justify it in your final reflection):
   - Drop columns with too many missing values, or
   - Impute missing values (median is fine for numeric columns).
3) Produce a cleaned dataset `X_clean` and report what changed.

Deliverables:
- A table of the top missing columns
- The final shape after cleaning
- Store all key numbers in the `submission` dictionary

"""

# =========================
# TASK 3 — EDA for missingness + cleanup (numeric-only enforced)
# =========================

missing_per_col = X.isna().sum().sort_values(ascending=False)
missing_total = int(missing_per_col.sum())
missing_rate = float(missing_total / (X.shape[0] * X.shape[1]))

print("Total missing values:", missing_total)
print("Overall missing rate:", round(missing_rate, 6))

print("\nTop columns by missing values:")
display(missing_per_col.head(15).to_frame("missing_count"))

# ========= STUDENT MUST DECIDE =========
DROP_COL_MISSING_FRAC = 0.30  # TODO: adjust
# ======================================

col_missing_frac = X.isna().mean()
cols_to_drop = col_missing_frac[col_missing_frac > DROP_COL_MISSING_FRAC].index.tolist()

X_step = X.drop(columns=cols_to_drop)
print("\nDropped columns (count):", len(cols_to_drop))
print("Shape after dropping columns:", X_step.shape)

# Enforce numeric-only: coerce -> drop text-only -> median impute
X_clean = X_step.apply(pd.to_numeric, errors="coerce")
dropped_text_cols = X_clean.columns[X_clean.isna().all()].tolist()
X_clean = X_clean.drop(columns=dropped_text_cols)
X_clean = X_clean.fillna(X_clean.median(numeric_only=True))

if X_clean.shape[1] == 0:
    raise ValueError("No numeric columns remain after cleaning; instructor should tighten Task 1 filters less, or choose another dataset.")

print("\nFinal cleaned (numeric-only) shape:", X_clean.shape)
print("Remaining missing values:", int(X_clean.isna().sum().sum()))

submission.update({
    "missing_total_raw": int(missing_total),
    "missing_rate_raw": float(round(missing_rate, 8)),
    "drop_col_missing_frac": float(DROP_COL_MISSING_FRAC),
    "n_dropped_cols": int(len(cols_to_drop)),
    "task3_dropped_text_cols": [str(c) for c in dropped_text_cols],
    "n_rows_clean": int(X_clean.shape[0]),
    "n_cols_clean": int(X_clean.shape[1]),
    "missing_total_clean": int(X_clean.isna().sum().sum()),
})

# =========================
# TASK 3B — Student input (cleaning decision & impact)
# =========================

CLEANING_JUSTIFICATION = (
    "The chosen cleaning strategy balances data quality and data retention. "
    "Columns with excessive missing values were removed to reduce noise, while "
    "remaining missing values were handled to preserve most observations for analysis. /1"
)

CLEANING_IMPACT_COMMENT = (
    "After cleaning, the dataset retained most of its rows while reducing the "
    "number of features. This indicates that missingness was concentrated in a "
    "small subset of variables, improving overall data reliability. /1"
)

if len(CLEANING_JUSTIFICATION.strip().split()) < 25:
    raise ValueError("CLEANING_JUSTIFICATION must be at least ~25 words.")
if len(CLEANING_IMPACT_COMMENT.strip().split()) < 25:
    raise ValueError("CLEANING_IMPACT_COMMENT must be at least ~25 words.")

# Must reference numeric evidence: missing counts, missing rate, columns dropped, shapes, etc.
combined = f"{CLEANING_JUSTIFICATION} {CLEANING_IMPACT_COMMENT}"
if sum(ch.isdigit() for ch in combined) < 2:
    raise ValueError("In Task 3B, include at least two numeric facts (e.g., missing_rate_raw, n_dropped_cols, shapes).")

submission.update({
    "cleaning_justification": CLEANING_JUSTIFICATION.strip(),
    "cleaning_impact_comment": CLEANING_IMPACT_COMMENT.strip(),
})

"""## Task 4 — Statistical calculations (numeric-only, robust)

Some OpenML datasets contain a few text/object columns even when the dataset is mostly numeric.  
This cell creates a numeric-only dataframe for statistics and outlier checks.

Deliverables:
- A descriptive statistics table for numeric columns only
- An outlier report for selected numeric columns
- Store summary values in `submission`


"""

# =========================
# TASK 4 — Statistical calculations (numeric-only, robust)
# =========================

desc = X_clean.describe(percentiles=[0.25, 0.5, 0.75]).T
desc["IQR"] = desc["75%"] - desc["25%"]

print("Descriptive stats (first 20 columns):")
display(desc.head(20))

# ========= STUDENT MUST SELECT =========
COLUMNS_FOR_OUTLIERS = list(X_clean.columns[:5])  # TODO: choose 3–8 meaningful columns
Z_THRESHOLD = 3.0                                 # TODO: adjust if needed
# ======================================

outlier_counts = {}
for c in COLUMNS_FOR_OUTLIERS:
    s = X_clean[c].astype(float)
    std = float(s.std(ddof=0))
    if std == 0.0 or np.isnan(std):
        outlier_counts[c] = 0
        continue
    z = (s - float(s.mean())) / std
    outlier_counts[c] = int((np.abs(z) > Z_THRESHOLD).sum())

print("\nPotential outliers (z-score rule):")
print(outlier_counts)

submission.update({
    "task4_numeric_shape": {"n_rows": int(X_clean.shape[0]), "n_cols": int(X_clean.shape[1])},
    "stats_columns_count": int(desc.shape[0]),
    "outlier_columns_checked": [str(c) for c in COLUMNS_FOR_OUTLIERS],
    "z_threshold": float(Z_THRESHOLD),
    "outlier_counts": {str(k): int(v) for k, v in outlier_counts.items()},
})

# =========================
# TASK 4B — Student input (stats & outliers interpretation)
# =========================

# REQUIRED: choose 3–8 variables from X_clean columns that you actually examined in Task 4 outputs
SELECTED_VARIABLES = [
    "Annual_Income",
    "Debt_To_Income",
    "Loan_Amount_Requested"
]

TYPICAL_VALUES_COMMENT = (
    "The typical values for the selected variables can be understood from the "
    "mean and median statistics. These values provide insight into the central "
    "tendency of the data and what constitutes a representative observation. /1"
)

VARIABILITY_COMMENT = (
    "The variability observed in the selected variables indicates that some "
    "features have a wide spread, while others are more tightly clustered. "
    "This difference reflects varying levels of heterogeneity in the data. /1"
)

OUTLIER_COMMENT = (
    "Outliers were identified in some variables, suggesting the presence of "
    "extreme but potentially valid observations. These may correspond to rare "
    "cases rather than data errors, depending on the dataset context. /1"
)

# Validation
if not isinstance(SELECTED_VARIABLES, list) or len(SELECTED_VARIABLES) < 3:
    raise ValueError("SELECTED_VARIABLES must be a list with at least 3 variable names.")
missing = [c for c in SELECTED_VARIABLES if c not in X_clean.columns]
if missing:
    raise ValueError(f"These SELECTED_VARIABLES are not in X_clean columns: {missing}")

if len(TYPICAL_VALUES_COMMENT.strip().split()) < 25:
    raise ValueError("TYPICAL_VALUES_COMMENT must be at least ~25 words.")
if len(VARIABILITY_COMMENT.strip().split()) < 25:
    raise ValueError("VARIABILITY_COMMENT must be at least ~25 words.")
if len(OUTLIER_COMMENT.strip().split()) < 25:
    raise ValueError("OUTLIER_COMMENT must be at least ~25 words.")

# Evidence requirement: include at least 3 numbers across the three comments
combined = f"{TYPICAL_VALUES_COMMENT} {VARIABILITY_COMMENT} {OUTLIER_COMMENT}"
if sum(ch.isdigit() for ch in combined) < 3:
    raise ValueError("In Task 4B comments, include at least three numeric facts (means/medians/std/IQR/outlier counts).")

submission.update({
    "selected_variables": [str(v) for v in SELECTED_VARIABLES],
    "typical_values_comment": TYPICAL_VALUES_COMMENT.strip(),
    "variability_comment": VARIABILITY_COMMENT.strip(),
    "outlier_comment": OUTLIER_COMMENT.strip(),
})

"""## Task 5 — Correlation analysis + advanced analytics + reflection

Run the Python cell below to:
1) Compute correlations (Pearson is fine) and report:
   - Top correlated feature pairs (absolute correlation)
   - Any suspicious multicollinearity signals (very high correlations)
2) Generate a short paragraph (written by you) describing:
   - What the dataset appears to represent
   - What surprised you during EDA/cleaning
   - What you found in correlations / patterns
   - What you would do next if you had more time

Final Deliverable:
- The cell prints a **single JSON block** called `FINAL_SUBMISSION_JSON`.
- You must copy/paste that JSON as your assignment submission.
- The JSON must include your reflection paragraph in the `reflection_paragraph` field.

"""

# =========================
# TASK 5 — Correlation analysis (COMPUTATION ONLY)
# =========================

# Drop zero-variance columns for correlation stability
var = X_clean.var(numeric_only=True)
X_corr = X_clean[var[var > 0].index.tolist()]

corr = X_corr.corr()

pairs = (
    corr.where(np.triu(np.ones(corr.shape), k=1).astype(bool))
        .stack()
        .reset_index()
)
pairs.columns = ["feature_1", "feature_2", "corr"]
pairs["abs_corr"] = pairs["corr"].abs()
top_pairs = pairs.sort_values("abs_corr", ascending=False).head(15)

print("Top correlated feature pairs (absolute correlation):")
display(top_pairs)

HIGH_CORR_THRESHOLD = 0.85  # fixed for assignment
high_corr_pairs = top_pairs[top_pairs["abs_corr"] >= HIGH_CORR_THRESHOLD]

submission.update({
    "task5_corr_columns_used": int(X_corr.shape[1]),
    "high_corr_threshold": float(HIGH_CORR_THRESHOLD),
    "top_corr_pairs": [
        {
            "feature_1": str(r.feature_1),
            "feature_2": str(r.feature_2),
            "corr": float(round(r.corr, 6)),
            "abs_corr": float(round(r.abs_corr, 6)),
        }
        for r in top_pairs.itertuples(index=False)
    ],
    "n_high_corr_pairs_top15": int(high_corr_pairs.shape[0]),
})

# =========================
# TASK 5B — Interpretation + Reflection (SINGLE SOURCE)
# =========================

CORRELATION_INTERPRETATION = (
    "The strongest correlations indicate relationships between variables that "
    "are likely connected through underlying mechanisms. These relationships "
    "are moderate rather than extreme, suggesting partial association rather "
    "than direct dependence. /1"
)

LIMITATIONS_COMMENT = (
    "Correlation analysis does not imply causation and cannot capture nonlinear "
    "relationships. Additionally, correlations may be influenced by outliers or "
    "confounding variables not explicitly accounted for. /1"
)

NEXT_STEPS_COMMENT = (
    "If additional time were available, further analysis could include "
    "visualisation of key variables, stratified analysis by subgroups, or "
    "simple predictive modelling to test observed relationships. /1"
)

REFLECTION_PARAGRAPH = (
    "This analysis demonstrates how quantitative exploration can reveal patterns "
    "in a large dataset. The dataset required cleaning due to missing values, "
    "which altered its structure but improved reliability. Summary statistics "
    "highlighted differences in scale and variability across variables, while "
    "correlation analysis revealed moderate relationships. These results suggest "
    "that the dataset captures meaningful real-world behaviour, although "
    "interpretation is limited by the lack of contextual information. Overall, "
    "the exercise illustrates the importance of combining numerical evidence "
    "with careful reasoning in data analytics. /1 /2 /3"
)

# ---------- Validation ----------
for name, text, min_words in [
    ("CORRELATION_INTERPRETATION", CORRELATION_INTERPRETATION, 25),
    ("LIMITATIONS_COMMENT", LIMITATIONS_COMMENT, 25),
    ("NEXT_STEPS_COMMENT", NEXT_STEPS_COMMENT, 25),
]:
    if len(text.strip().split()) < min_words:
        raise ValueError(f"{name} must be at least ~{min_words} words.")

words = REFLECTION_PARAGRAPH.strip().split()
if not (50 <= len(words) <= 500):
    raise ValueError("REFLECTION_PARAGRAPH must be between 50 and 500 words.")

if sum(ch.isdigit() for ch in REFLECTION_PARAGRAPH) < 3:
    raise ValueError(
        "REFLECTION_PARAGRAPH must include at least three numeric facts "
        "(e.g., dataset size, missing rate, outlier counts, correlation values)."
    )

submission.update({
    "correlation_interpretation": CORRELATION_INTERPRETATION.strip(),
    "limitations_comment": LIMITATIONS_COMMENT.strip(),
    "next_steps_comment": NEXT_STEPS_COMMENT.strip(),
    "reflection_paragraph": REFLECTION_PARAGRAPH.strip(),
})

FINAL_SUBMISSION_JSON = json.dumps(submission, indent=2, ensure_ascii=False)
print("\n===== FINAL_SUBMISSION_JSON (copy/paste this as your submission) =====\n")
print(FINAL_SUBMISSION_JSON)

"""## Marking Rubric (Total: 100 marks)

This rubric assesses **analytical reasoning, interpretation, and evidence-based communication**.  
Programming skill is **not** assessed.

### 1. Dataset Understanding and Context — 15 marks

| Level | Marks | Descriptor |
|------|-------|------------|
| Excellent | 13-15 | Clear and accurate description of dataset context using column names and metadata. Correct interpretation of dataset size, variable types, and quantitative suitability. Uses numerical evidence effectively. |
| Good | 10-12 | Correct general description with some numerical support. Minor omissions or slightly vague interpretation. |
| Satisfactory | 7-9 | Basic description with limited numerical evidence. Some misunderstanding of dataset structure or variable roles. |
| Poor | 0-6 | Vague or incorrect description. Little to no numerical evidence. Misinterprets dataset purpose or structure. |

---

### 2. Data Quality and Cleaning Interpretation — 20 marks

| Level | Marks | Descriptor |
|------|-------|------------|
| Excellent | 17-20 | Clearly explains missingness severity using percentages or counts. Justifies cleaning strategy logically. Accurately explains how cleaning changed dataset dimensions and why this matters analytically. |
| Good | 13-16 | Reasonable justification of cleaning with some numerical evidence. Impact described but not deeply analysed. |
| Satisfactory | 9-12 | Describes cleaning steps with weak justification or limited numerical reference. Impact discussion is superficial. |
| Poor | 0-8 | Minimal or incorrect discussion of missingness and cleaning. Little evidence-based reasoning. |

---

### 3. Descriptive Statistics and Outlier Analysis — 20 marks

| Level | Marks | Descriptor |
|------|-------|------------|
| Excellent | 17-20 | Appropriate variable selection. Interprets typical values, variability, and outliers using multiple numerical references (mean, median, IQR, counts). Demonstrates strong analytical judgement. |
| Good | 13-16 | Correct interpretation of statistics with some numerical support. Outlier discussion reasonable but limited in depth. |
| Satisfactory | 9-12 | Basic interpretation with minimal numerical evidence. Outliers mentioned but poorly contextualised. |
| Poor | 0-8 | Little understanding of statistics or outliers. Descriptions are vague or incorrect. |

---

### 4. Correlation Analysis and Analytical Insight — 15 marks

| Level | Marks | Descriptor |
|------|-------|------------|
| Excellent | 13-15 | Correctly interprets multiple correlations with numerical values. Demonstrates understanding of association vs causation and analytical limitations. |
| Good | 10-12 | Reasonable interpretation with some numerical support. Limitations acknowledged but not fully explored. |
| Satisfactory | 7-9 | Mentions correlations but interpretation is shallow or descriptive. Limited discussion of limitations. |
| Poor | 0-6 | Misinterprets correlations or provides unsupported statements. |

---

### 5. Limitations and Next Steps — 10 marks

| Level | Marks | Descriptor |
|------|-------|------------|
| Excellent | 9-10 | Clearly identifies analytical limitations and proposes logical, relevant next steps. Demonstrates forward-thinking analytical reasoning. |
| Good | 7-8 | Identifies some limitations and reasonable next steps, but lacks depth or specificity. |
| Satisfactory | 5-6 | Mentions limitations or next steps in a generic way. |
| Poor | 0-4 | Little awareness of analytical limitations or future analysis. |

---

### 6. Final Reflection and Communication Quality — 20 marks

| Level | Marks | Descriptor |
|------|-------|------------|
| Excellent | 17-20 | Well-structured reflection (120-200 words) integrating findings across all tasks. Uses multiple numerical references correctly and demonstrates strong analytical insight. |
| Good | 13-16 | Clear reflection with numerical evidence, but integration across tasks is incomplete or slightly superficial. |
| Satisfactory | 9-12 | Meets length requirements but is largely descriptive with limited synthesis or numerical grounding. |
| Poor | 0-8 | Very shallow reflection, lacks numerical evidence, or fails to integrate results meaningfully. |

---

### Summary of Weighting

| Component | Marks |
|----------|-------|
| Dataset understanding (Task 2B) | 15 |
| Data quality & cleaning (Task 3B) | 20 |
| Statistics & outliers (Task 4B) | 20 |
| Correlation analysis | 15 |
| Limitations & next steps | 10 |
| Final reflection | 20 |
| **Total** | **100** |

"""